### PR TITLE
Missing localization and words fixing

### PR DESCRIPTION
**Pull request by DrParadox7**
Added Platinum Pipe Localization.
Changed "Material is **changing** behind this rock" to **hiding**.
Fixed capitalization in Retriever.

### CODE REVIEW

**Comment by DrParadox7** [comment]
image

**Review by TheDarkDnKTv — COMMENTED** [review]
Why did you decide to change `retriever` to `Retriever`?

**Comment by DrParadox7** [comment]
Let's look at some other localizations in GT:
"Electric Type Filter"
"Bronze Workbench"
"Advanced Crafting Table"

Wouldn't you agree that "Advanced retriever" sticks out like a sore thumb?

**Comment by DrParadox7** [comment]
Also line 88:
metatileentity.GT_E_Craftingtable.name=Electric Craftingtable
should be:
metatileentity.GT_E_Craftingtable.name=Electric Crafting Table

Those are all the typos I have found

**Pull request closed without merging**
